-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]

TEAM_CITIZEN = DarkRP.createJob("Prisonnier", {
    color = Color(20, 150, 20, 255),
    model = {
		"models/jbarnes/player/prisoners/jumpsuitm7.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm9.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm5.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm1.mdl"
    },
    description = [[Vous n'avez aucun emploi.]],
    weapons = {"weapon_arc_atmcard"},
    command = "citizen",
    max = 0,
    salary = 20,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Citizens",
})

TEAM_PRISONDEALEUR = DarkRP.createJob("Prisonnier Dealeur", {
    color = Color(20, 150, 20, 255),
     model = {
		"models/jbarnes/player/prisoners/jumpsuitm7.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm9.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm5.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm1.mdl"
    },
    description = [[Vous ete le dealeur de la prison]],
    weapons = {},
    command = "dealeur",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "PrisonnierDealeur",
})

TEAM_PRISONVENDEUR = DarkRP.createJob("Prisonnier Vendeur D'armes", {
    color = Color(20, 150, 20, 255),
   model = {
		"models/jbarnes/player/prisoners/jumpsuitm7.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm9.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm5.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm1.mdl"
    },
    description = [[Vous ete le dealeur de la prison]],
    weapons = {},
    command = "vendeur",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "PrisonnierVendeur",
})

TEAM_PRISONVIOLEUR = DarkRP.createJob("Prisonnier violeur", {
    color = Color(20, 150, 20, 255),
    model = {
		"models/jbarnes/player/prisoners/jumpsuitm7.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm9.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm5.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm1.mdl"
    },
    description = [[Vous ete le dealeur de la prison]],
    weapons = {},
    command = "violeur",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "PrisonnierVioleur",
})

TEAM_PRISONVOLEUR = DarkRP.createJob("Prisonnier voleur", {
    color = Color(20, 150, 20, 255),
    model = {
		"models/jbarnes/player/prisoners/jumpsuitm7.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm9.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm5.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm1.mdl"
    },
    description = [[Vous ete le dealeur de la prison]],
    weapons = {},
    command = "voleur",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "PrisonnierVoleur",
})

TEAM_PRISONGAY = DarkRP.createJob("Prisonnier Gay", {
    color = Color(20, 150, 20, 255),
    model = {
		"models/jbarnes/player/prisoners/jumpsuitm7.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm9.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm5.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm1.mdl"
    },
    description = [[Vous ete le dealeur de la prison]],
    weapons = {},
    command = "gay",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "PrisonnierGay",
})

TEAM_CHIMISTE = DarkRP.createJob("Prisonnier Heinsenberg", {
    color = Color(20, 150, 20, 255),
    model = {
		"models/jbarnes/player/prisoners/jumpsuitm7.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm9.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm5.mdl",
		"models/jbarnes/player/prisoners/jumpsuitm1.mdl"
    },
    description = [[Vous ete le dealeur de la prison]],
    weapons = {},
    command = "Heisenberg",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Heinsenberg",
})

TEAM_GARDIEN = DarkRP.createJob("Gardien De Prison", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/bfh_mechanic.mdl"},
    description = [[Vous ete le gardien de la prison]],
    weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
    command = "gardien",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "GardienPrison",
})

TEAM_GARDIENCORROMPUE = DarkRP.createJob("Gardien Corrompu", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/bfh_mechanic.mdl"},
    description = [[Vous ete corrompu]],
    weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
    command = "corrompu",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "GardienCorrompu",
})

TEAM_CHEFGARDIENS = DarkRP.createJob("Chef des gardiens", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/bfh_enforcer.mdl"},
    description = [[vous gerer vo's troupes]],
    weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
    command = "chefgardiens",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "ChefGardiens",
})

TEAM_UNITEANTI = DarkRP.createJob("Unite anti-emeute", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/bfh_enforcer.mdl"},
    description = [[Vous ete corrompu]],
    weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
    command = "antiemeute",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Uniteantiemeute",
})

TEAM_MIRADOR = DarkRP.createJob("Mirador", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/bfh_pro.mdl"},
    description = [[Vous ete corrompu]],
    weapons = {"arrest_stick", "unarrest_stick", "weapon_glock2", "stunstick", "door_ram", "weaponchecker"},
    command = "mirador",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Mirador",
})

TEAM_MEDIC = DarkRP.createJob("Medecin", {
    color = Color(47, 79, 79, 255),
    model = "models/player/kleiner.mdl",
    description = [[With your medical knowledge you work to restore players to full health.
        Without a medic, people cannot be healed.
        Left click with the Medical Kit to heal other players.
        Right click with the Medical Kit to heal yourself.]],
    weapons = {"med_kit", "env_cubemap"},
    command = "medic",
    max = 3,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    medic = true,
    category = "Citizens",
})

TEAM_VENDEURPOLICE = DarkRP.createJob("Vendeur d'armes de la police", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/bfh_mechanic.mdl"},
    description = [[Vous ete corrompu]],
    weapons = {"models/weapons/w_kriss_vector.mdl"},
    command = "vendeurpol",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Vendeurpol",
})

TEAM_ADMIN = DarkRP.createJob("Administrateur", {
   color = Color(255, 0, 0, 255),
   model = {"models/player/jesus/jesus.mdl"},
   description = [[Merci d'appeler un admin pour tout probleme (/// + la raison)]],
   weapons = {"models/weapons/w_kriss_vector.mdl"},
   command = "admin",
   max = 2,
   salary = 250,
   admin = 1,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Admin",
})

if not DarkRP.disabledDefaults["modules"]["hungermod"] then
    TEAM_COOK = DarkRP.createJob("Cook", {
        color = Color(238, 99, 99, 255),
        model = "models/player/mossman.mdl",
        description = [[As a cook, it is your responsibility to feed the other members of your city.
            You can spawn a microwave and sell the food you make:
            /buymicrowave]],
        weapons = {},
        command = "cook",
        max = 2,
        salary = 45,
        admin = 0,
        vote = false,
        hasLicense = false,
        cook = true
    })
end

-- Compatibility for when default teams are disabled
TEAM_CITIZEN       = TEAM_CIVIL      or -1
TEAM_PRISONVIOLEUR = TEAM_PRISONVIOLEUR or -1
TEAM_PRISONVENDEUR = TEAM_PRISONVENDEUR or -1
TEAM_PRISONDEALEUR = TEAM_PRISONDEALEUR or -1
TEAM_MIRADOR        = TEAM_MIRADOR   or -1
TEAM_UNITEANTI      = TEAM_UNITEANTI     or -1
TEAM_GARDIEN      = TEAM_GARDIEN     or -1
TEAM_PRISONGAY      = TEAM_PRISONGAY     or -1
TEAM_PRISONVOLEUR      = TEAM_PRISONVOLEUR     or -1
TEAM_CHEFGARDIENS           = TEAM_CHEFGARDIENS      or -1
TEAM_PRISONMETH =       TEAM_PRISONMETH or -1
TEAM_GUN           = TEAM_GUN      or -1
TEAM_VENDEURPOLICE = TEAM_VENDEURPOLICE or -1
TEAM_MEDIC         = TEAM_MEDIC    or -1
TEAM_GARDIENCORROMPUE         = TEAM_GARDIENCORROMPUE    or -1
TEAM_MAYOR         = TEAM_MAYOR    or -1
TEAM_HOBO          = TEAM_HOBO     or -1


/*
--------------------------------------------------------
HOW TO MAKE A DOOR GROUP
--------------------------------------------------------
AddDoorGroup("NAME OF THE GROUP HERE, you see this when looking at a door", Team1, Team2, team3, team4, etc.)


The default door groups, can also be used as examples:
*/
AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
AddDoorGroup("Gundealer only", TEAM_GUN)


/*
--------------------------------------------------------
HOW TO MAKE AN AGENDA
--------------------------------------------------------
DarkRP.createAgenda(Title of the agenda, Manager (who edits it), Listeners (the ones who just see and follow the agenda))
It's possible to have multiple managers. In that case you have to put all the managers in '{}' (see Police agenda)

The default agendas, can also be used as examples:
*/
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})


/*
---------------------------------------------------------------------------
HOW TO MAKE A GROUP CHAT
---------------------------------------------------------------------------
Pick one!
DarkRP.createGroupChat(List of team variables separated by comma)

or

DarkRP.createGroupChat(a function with ply as argument that returns whether a random player is in one chat group)
This one is for people who know how to script Lua.

*/
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

/*---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------*/
GAMEMODE.DefaultTeam = TEAM_CITIZEN

/*---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------*/
GAMEMODE.CivilProtection = {
	[TEAM_POLICE] = true,
	[TEAM_CHIEF] = true,
	[TEAM_MAYOR] = true,
}

/*---------------------------------------------------------------------------
Enable hitman goodies on this team
---------------------------------------------------------------------------*/
DarkRP.addHitmanTeam(TEAM_MOB)

/*---------------------------------------------------------------------------
Default demote groups
---------------------------------------------------------------------------*/
DarkRP.createDemoteGroup("Cops", {TEAM_POLICE, TEAM_CHIEF})
DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})

/*---------------------------------------------------------------------------
Default categories
---------------------------------------------------------------------------*/
DarkRP.createCategory{
	name = "Citizens",
	categorises = "jobs",
	startExpanded = true,
	color = Color(0, 107, 0, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 100,
}

DarkRP.createCategory{
	name = "PrisonnierDealeur",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 101,
}
DarkRP.createCategory{
	name = "PrisonnierTrafiquant",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 102,
}
DarkRP.createCategory{
	name = "PrisonnierVendeur",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 103,
}

DarkRP.createCategory{
	name = "PrisonnierVioleur",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}

DarkRP.createCategory{
	name = "Vendeurpol",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}

DarkRP.createCategory{
	name = "Mirador",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}

DarkRP.createCategory{
	name = "ChefGardiens",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}

DarkRP.createCategory{
	name = "Uniteantiemeute",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}

DarkRP.createCategory{
	name = "GardienCorrompu",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}

DarkRP.createCategory{
	name = "Heinsenberg",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}

DarkRP.createCategory{
	name = "GardienPrison",
	categorises = "jobs",
	startExpanded = true,
	color = Color(25, 25, 170, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 104,
}